TIMEOUT = 10

TEAMCITY_API = "app/rest"
TEAMCITY_API_VERSION = "latest"

TEAMCITY_BASIC_AUTH = "httpAuth"
TEAMCITY_GUEST_AUTH = "guestAuth"

TEAMCITY_SERVER_INFO_API = "server"
TEAMCITY_PLUGINS_API = "{0}/plugins".format(TEAMCITY_SERVER_INFO_API)
